$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:

  svm:
    type: object
    properties:
      kernel:
        type: string

    required:
      - kernel
